### ISSUE TITLE
[BUGS] Installing LVS and ACF-3 on a dedicated server causes strange issues.

### ISSUE THREAD

**Issue by TheTeleportingFish** [ACF-Team/ACF-3#375] opened 2023-09-15 07:41 UTC
### **Installing LVS and ACF-3 on a dedicated server causes strange issues.**

**Short Description**
Seems to break a lot of ACF functions, engines don't throttle, weapons don't have mass, collision boxes seem to not initialize.

**Branch and Version**
Master - 11fefdc
Merge pull request [](https://github.com/Stooberton/ACF-3/pull/372) from yoseij/master

**Console Error Logs**
_The only error thrown seems to be -_
```
[acf-3] lua/vgui/dcombobox.lua:93: bad argument #1 to 'SetText' (string expected, got nil)
  
SetText - [C]:-1
ChooseOption - lua/vgui/dcombobox.lua:93
ChooseOptionID - lua/vgui/dcombobox.lua:106
SetCustomValue - addons/acf-3/lua/acf/menu/items_cl/settings.lua:124
UpdatePanels - addons/acf-3/lua/acf/core/networking/data_vars/panel_functions_cl.lua:175
fn - addons/acf-3/lua/acf/core/networking/data_vars/panel_functions_cl.lua:227
Run - addons/ulib/lua/ulib/shared/hook.lua:109
SetFunction - addons/acf-3/lua/acf/core/networking/data_vars/data_vars_cl.lua:153
unknown - addons/acf-3/lua/acf/core/networking/data_vars/panel_functions_cl.lua:29

Timer Failed! [ACF Refresh Data Vars][@addons/acf-3/lua/acf/core/networking/data_vars/panel_functions_cl.lua (line 46)]
```
_This error is thrown when trying to change the server game mode setting._

**How to Reproduce**
Install latest ACF version with latest version of LVS, on a dedicated server.

**Screenshots**
![3DjDRHO](https://github.com/Stooberton/ACF-3/assets/20102267/8680689a-85ad-44c0-9d2c-c025989db8e7)

**Comment by thecraftianman** [comment] 2023-09-16 01:22
I can't seem to reproduce any of these issues on a server that has the latest versions of both; are you certain that something else isn't the problem?

**Comment by BamsTheSergal** [comment] 2023-09-17 06:20
seems to be cause he's using linux 64 and getting the issue.

**Comment by thecraftianman** [comment] 2024-01-26 04:19
Is this still an issue on the latest versions of ACF/LVS/Gmod?

**Comment by thecraftianman** [comment] 2024-03-27 18:45
After trying to dig a bit deeper, I'm told that the problem appeared to have resolved itself, so I'm closing this issue.

**Closed by thecraftianman** 2024-03-27 18:45 UTC
Labels: bug, can't replicate, info needed
